[VERSION]
Version=V1.0.0-20170831

[LOG] 
;LogLevel, 0-Fatal 1-Error 2-Warn 3-Info 4-Trace 5-Debug 6-All
LogLevel=5
;If output position info(filename/linenum), 1-Yes 0-No
LogPosition=1
;Log dir
DebugLogDir=/home/log/debug
ErrorLogDir=/home/log/error
[SOCKET]
port=9999
